version: '3.8'
services:
    db:
        image: mysql
        restart: always
        environment:
            # MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: ropuch
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD:
        ports:
            - "8080:80"
